### ISSUE TITLE
Uses old compiled C code for cache

### ISSUE THREAD

**Issue by davidw** [ipinfo/ruby#16]
```In Gemfile:
  IPinfo was resolved to 0.1.2, which depends on
    lrucache was resolved to 0.1.4, which depends on
      PriorityQueue
```
PriorityQueue won't compile with my version of Ruby `2.6.5p114`.

Perhaps it should be left to the user to cache results?

**Comment by UmanShahzad** [comment]
lru_redux is used in `0.1.3`; let me know if it produces another similar issue.
